### ISSUE TITLE
picture elements

### ISSUE THREAD

**Issue by DanielRuf** [RevillWeb/img-2#7]
Does this work with all configs even in picture tags and as video fallback and so on?

**Comment by RevillWeb** [comment]
Hi Daniel, thanks for taking the time to post this question. I haven't actually tried this but unfortunately, I don't think it will.

A picture element's permitted content is 

> Zero or more <source> elements, followed by one <img> element

And a video element has similar restrictions.

Which obviously doesn't include `<img-2>`. This is a problem I'd like to resolve by using [customized built-in elements](https://blog.revillweb.com/extending-native-dom-elements-with-web-components-233350c8e86a) instead of [autonomous custom elements](https://www.w3.org/TR/custom-elements/#custom-elements-autonomous-example) that it currently uses.
